apiVersion: apps/v1
kind: Deployment
metadata:
  name: ping-pong-application
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: ping-pong-application
  template:
    metadata:
      labels:
        app: ping-pong-application
    spec:
      volumes:
        - name: shared-image
          persistentVolumeClaim:
            claimName: main-application-claim
      containers:
        - name: ping-pong-application
          image: nanyangcn/ping-pong-application
          volumeMounts:
          - name: shared-image
            mountPath: /usr/src/app/files