apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: main-application-ing
spec:
  rules:
  - http:
      paths:
      - path: /
        backend:
          serviceName: main-application-svc
          servicePort: 2345