apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: main-application-namespace
  name: main-application-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi